2022-06-21 15:32:17,676 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-06-21 15:32:17,679 INFO supervisord started with pid 9
2022-06-21 15:32:18,685 INFO spawned: 'nginx' with pid 12
2022-06-21 15:32:18,689 INFO spawned: 'app' with pid 13
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 72, in register
    self.register_transition('send_global_parms', Role.COORDINATOR)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 293, in register_transition
    self.log(f'target state {target} not found', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 21.06.22 15:32:19] [Level: fatal] target state send_global_parms not found
2022-06-21 15:32:19,157 INFO exited: app (exit status 1; not expected)
2022-06-21 15:32:20,160 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-21 15:32:20,166 INFO spawned: 'app' with pid 22
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 72, in register
    self.register_transition('send_global_parms', Role.COORDINATOR)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 293, in register_transition
    self.log(f'target state {target} not found', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 21.06.22 15:32:20] [Level: fatal] target state send_global_parms not found
2022-06-21 15:32:20,617 INFO exited: app (exit status 1; not expected)
2022-06-21 15:32:22,629 INFO spawned: 'app' with pid 27
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 72, in register
    self.register_transition('send_global_parms', Role.COORDINATOR)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 293, in register_transition
    self.log(f'target state {target} not found', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 21.06.22 15:32:23] [Level: fatal] target state send_global_parms not found
2022-06-21 15:32:23,115 INFO exited: app (exit status 1; not expected)
2022-06-21 15:32:26,126 INFO spawned: 'app' with pid 32
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 72, in register
    self.register_transition('send_global_parms', Role.COORDINATOR)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 293, in register_transition
    self.log(f'target state {target} not found', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 21.06.22 15:32:26] [Level: fatal] target state send_global_parms not found
2022-06-21 15:32:26,577 INFO exited: app (exit status 1; not expected)
2022-06-21 15:32:27,580 INFO gave up: app entered FATAL state, too many start retries too quickly
