2022-06-22 12:32:37,825 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-06-22 12:32:37,828 INFO supervisord started with pid 8
2022-06-22 12:32:38,835 INFO spawned: 'nginx' with pid 11
2022-06-22 12:32:38,839 INFO spawned: 'app' with pid 12
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:32:39] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:32:39,898 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:32:39,898 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:32:39,898 INFO exited: app (exit status 1; not expected)
2022-06-22 12:32:40,900 INFO spawned: 'app' with pid 24
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:32:41] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:32:41,884 INFO exited: app (exit status 1; not expected)
2022-06-22 12:32:42,887 INFO spawned: 'app' with pid 32
2022-06-22 12:32:43,889 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:32:43] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:32:44,094 INFO exited: app (exit status 1; not expected)
2022-06-22 12:32:45,101 INFO spawned: 'app' with pid 40
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:32:45] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:32:46,040 INFO exited: app (exit status 1; not expected)
2022-06-22 12:32:47,042 INFO spawned: 'app' with pid 48
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:32:47] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:32:47,972 INFO exited: app (exit status 1; not expected)
2022-06-22 12:32:49,977 INFO spawned: 'app' with pid 56
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:32:50] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:32:51,125 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:32:51,126 INFO exited: app (exit status 1; not expected)
2022-06-22 12:32:52,130 INFO spawned: 'app' with pid 64
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:32:53] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:32:53,284 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:32:53,284 INFO exited: app (exit status 1; not expected)
2022-06-22 12:32:54,296 INFO spawned: 'app' with pid 72
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:32:55] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:32:55,352 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:32:55,352 INFO exited: app (exit status 1; not expected)
2022-06-22 12:32:56,357 INFO spawned: 'app' with pid 80
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:32:57] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:32:57,425 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:32:57,426 INFO exited: app (exit status 1; not expected)
2022-06-22 12:32:58,434 INFO spawned: 'app' with pid 88
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:32:59] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:32:59,553 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:32:59,554 INFO exited: app (exit status 1; not expected)
2022-06-22 12:33:00,566 INFO spawned: 'app' with pid 96
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:33:01] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:33:01,597 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:33:01,597 INFO exited: app (exit status 1; not expected)
2022-06-22 12:33:02,604 INFO spawned: 'app' with pid 104
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:33:03] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:33:03,650 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:33:03,651 INFO exited: app (exit status 1; not expected)
2022-06-22 12:33:04,654 INFO spawned: 'app' with pid 112
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:33:05] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:33:05,728 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:33:05,730 INFO exited: app (exit status 1; not expected)
2022-06-22 12:33:06,733 INFO spawned: 'app' with pid 120
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:33:07] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:33:07,810 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:33:07,810 INFO exited: app (exit status 1; not expected)
2022-06-22 12:33:08,817 INFO spawned: 'app' with pid 128
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:33:09] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:33:09,797 INFO exited: app (exit status 1; not expected)
2022-06-22 12:33:10,806 INFO spawned: 'app' with pid 136
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:33:11] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:33:11,765 INFO exited: app (exit status 1; not expected)
2022-06-22 12:33:13,770 INFO spawned: 'app' with pid 144
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:33:14] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:33:14,849 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:33:14,852 INFO exited: app (exit status 1; not expected)
2022-06-22 12:33:15,864 INFO spawned: 'app' with pid 152
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
2022-06-22 12:33:16,860 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:33:16] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:33:17,059 INFO exited: app (exit status 1; not expected)
2022-06-22 12:33:18,065 INFO spawned: 'app' with pid 160
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:33:18] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:33:19,193 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:33:19,194 INFO exited: app (exit status 1; not expected)
2022-06-22 12:33:20,200 INFO spawned: 'app' with pid 168
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:33:21] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:33:21,370 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:33:21,371 INFO exited: app (exit status 1; not expected)
2022-06-22 12:33:22,374 INFO spawned: 'app' with pid 176
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:33:23] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:33:23,521 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:33:23,522 INFO exited: app (exit status 1; not expected)
2022-06-22 12:33:24,526 INFO spawned: 'app' with pid 184
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:33:25] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:33:25,547 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:33:25,547 INFO exited: app (exit status 1; not expected)
2022-06-22 12:33:26,552 INFO spawned: 'app' with pid 192
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:33:27] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:33:27,550 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:33:27,728 INFO exited: app (exit status 1; not expected)
2022-06-22 12:33:28,736 INFO spawned: 'app' with pid 200
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:33:29] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:33:29,793 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:33:29,802 INFO exited: app (exit status 1; not expected)
2022-06-22 12:33:30,816 INFO spawned: 'app' with pid 208
2022-06-22 12:33:31,818 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:33:31] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:33:32,055 INFO exited: app (exit status 1; not expected)
2022-06-22 12:33:33,064 INFO spawned: 'app' with pid 216
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:33:33] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:33:34,003 INFO exited: app (exit status 1; not expected)
2022-06-22 12:33:35,010 INFO spawned: 'app' with pid 224
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:33:35] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:33:36,944 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:33:36,945 INFO exited: app (exit status 1; not expected)
2022-06-22 12:33:37,949 INFO spawned: 'app' with pid 232
2022-06-22 12:33:38,953 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:33:39] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:33:39,288 INFO exited: app (exit status 1; not expected)
2022-06-22 12:33:40,291 INFO spawned: 'app' with pid 240
2022-06-22 12:33:41,292 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:33:41] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:33:41,537 INFO exited: app (exit status 1; not expected)
2022-06-22 12:33:42,539 INFO spawned: 'app' with pid 248
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:33:43] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:33:43,549 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:33:43,549 INFO exited: app (exit status 1; not expected)
2022-06-22 12:33:44,553 INFO spawned: 'app' with pid 256
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:33:45] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:33:45,528 INFO exited: app (exit status 1; not expected)
2022-06-22 12:33:46,531 INFO spawned: 'app' with pid 264
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:33:47] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:33:47,680 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:33:47,682 INFO exited: app (exit status 1; not expected)
2022-06-22 12:33:48,685 INFO spawned: 'app' with pid 272
2022-06-22 12:33:49,686 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 108, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:33:49] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:33:49,986 INFO exited: app (exit status 1; not expected)
