2022-06-22 12:29:14,495 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-06-22 12:29:14,499 INFO supervisord started with pid 9
2022-06-22 12:29:15,503 INFO spawned: 'nginx' with pid 12
2022-06-22 12:29:15,505 INFO spawned: 'app' with pid 13
2022-06-22 12:29:16,526 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:29:16,526 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:29:16] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:29:16,755 INFO exited: app (exit status 1; not expected)
2022-06-22 12:29:17,758 INFO spawned: 'app' with pid 25
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:29:18] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:29:18,933 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:29:18,933 INFO exited: app (exit status 1; not expected)
2022-06-22 12:29:19,937 INFO spawned: 'app' with pid 33
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:29:20] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:29:20,989 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:29:20,989 INFO exited: app (exit status 1; not expected)
2022-06-22 12:29:21,991 INFO spawned: 'app' with pid 41
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:29:22] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:29:23,106 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:29:23,106 INFO exited: app (exit status 1; not expected)
2022-06-22 12:29:24,109 INFO spawned: 'app' with pid 49
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:29:24] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:29:25,139 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:29:25,139 INFO exited: app (exit status 1; not expected)
2022-06-22 12:29:26,141 INFO spawned: 'app' with pid 57
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:29:26] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:29:27,132 INFO exited: app (exit status 1; not expected)
2022-06-22 12:29:28,136 INFO spawned: 'app' with pid 65
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:29:29] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:29:29,224 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:29:29,224 INFO exited: app (exit status 1; not expected)
2022-06-22 12:29:30,227 INFO spawned: 'app' with pid 73
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:29:31] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:29:31,262 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:29:31,262 INFO exited: app (exit status 1; not expected)
2022-06-22 12:29:32,266 INFO spawned: 'app' with pid 81
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:29:33] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:29:33,266 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:29:33,266 INFO exited: app (exit status 1; not expected)
2022-06-22 12:29:34,269 INFO spawned: 'app' with pid 89
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:29:35] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:29:35,302 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:29:35,302 INFO exited: app (exit status 1; not expected)
2022-06-22 12:29:36,304 INFO spawned: 'app' with pid 97
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:29:37] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:29:37,363 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:29:37,364 INFO exited: app (exit status 1; not expected)
2022-06-22 12:29:38,368 INFO spawned: 'app' with pid 105
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:29:39] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:29:39,388 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:29:39,388 INFO exited: app (exit status 1; not expected)
2022-06-22 12:29:40,391 INFO spawned: 'app' with pid 113
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:29:41] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:29:41,466 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:29:41,466 INFO exited: app (exit status 1; not expected)
2022-06-22 12:29:42,469 INFO spawned: 'app' with pid 121
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:29:43] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:29:43,500 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:29:43,501 INFO exited: app (exit status 1; not expected)
2022-06-22 12:29:44,509 INFO spawned: 'app' with pid 129
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:29:45] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:29:45,627 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:29:45,628 INFO exited: app (exit status 1; not expected)
2022-06-22 12:29:46,637 INFO spawned: 'app' with pid 137
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:29:47] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:29:47,706 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:29:47,706 INFO exited: app (exit status 1; not expected)
2022-06-22 12:29:48,712 INFO spawned: 'app' with pid 145
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:29:49] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:29:49,915 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:29:49,916 INFO exited: app (exit status 1; not expected)
2022-06-22 12:29:50,920 INFO spawned: 'app' with pid 153
2022-06-22 12:29:51,924 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:29:52] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:29:52,338 INFO exited: app (exit status 1; not expected)
2022-06-22 12:29:53,341 INFO spawned: 'app' with pid 161
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:29:54] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:29:54,512 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:29:54,512 INFO exited: app (exit status 1; not expected)
2022-06-22 12:29:55,515 INFO spawned: 'app' with pid 169
2022-06-22 12:29:56,516 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:29:56] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:29:56,777 INFO exited: app (exit status 1; not expected)
2022-06-22 12:29:57,779 INFO spawned: 'app' with pid 177
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:29:58] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:29:58,912 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:29:58,913 INFO exited: app (exit status 1; not expected)
2022-06-22 12:29:59,915 INFO spawned: 'app' with pid 185
2022-06-22 12:30:00,917 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:30:00] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:30:01,176 INFO exited: app (exit status 1; not expected)
2022-06-22 12:30:02,179 INFO spawned: 'app' with pid 193
2022-06-22 12:30:03,182 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:30:03] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:30:03,372 INFO exited: app (exit status 1; not expected)
2022-06-22 12:30:04,375 INFO spawned: 'app' with pid 201
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:30:05] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:30:05,513 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:30:05,513 INFO exited: app (exit status 1; not expected)
2022-06-22 12:30:06,515 INFO spawned: 'app' with pid 209
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:30:07] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:30:07,639 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:30:07,640 INFO exited: app (exit status 1; not expected)
2022-06-22 12:30:08,649 INFO spawned: 'app' with pid 217
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:30:09] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:30:09,673 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:30:09,674 INFO exited: app (exit status 1; not expected)
2022-06-22 12:30:10,677 INFO spawned: 'app' with pid 225
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:30:11] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:30:11,769 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:30:11,771 INFO exited: app (exit status 1; not expected)
2022-06-22 12:30:12,775 INFO spawned: 'app' with pid 233
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:30:13] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:30:13,775 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:30:13,933 INFO exited: app (exit status 1; not expected)
2022-06-22 12:30:14,936 INFO spawned: 'app' with pid 241
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:30:15] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:30:16,077 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:30:16,080 INFO exited: app (exit status 1; not expected)
2022-06-22 12:30:17,099 INFO spawned: 'app' with pid 249
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:30:18] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:30:18,254 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:30:18,255 INFO exited: app (exit status 1; not expected)
2022-06-22 12:30:19,257 INFO spawned: 'app' with pid 257
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:30:20] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:30:20,213 INFO exited: app (exit status 1; not expected)
2022-06-22 12:30:21,216 INFO spawned: 'app' with pid 265
2022-06-22 12:30:22,217 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:30:22] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:30:22,575 INFO exited: app (exit status 1; not expected)
2022-06-22 12:30:23,582 INFO spawned: 'app' with pid 273
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 109, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:30:24] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:30:24,510 INFO exited: app (exit status 1; not expected)
