2022-06-22 12:27:55,834 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-06-22 12:27:55,839 INFO supervisord started with pid 7
2022-06-22 12:27:56,843 INFO spawned: 'nginx' with pid 10
2022-06-22 12:27:56,845 INFO spawned: 'app' with pid 11
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:27:57] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:27:57,962 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:27:57,962 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:27:57,962 INFO exited: app (exit status 1; not expected)
2022-06-22 12:27:58,965 INFO spawned: 'app' with pid 23
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:27:59] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:27:59,869 INFO exited: app (exit status 1; not expected)
2022-06-22 12:28:00,877 INFO spawned: 'app' with pid 31
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:28:01] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:28:01,914 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:28:01,914 INFO exited: app (exit status 1; not expected)
2022-06-22 12:28:02,921 INFO spawned: 'app' with pid 39
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:28:03] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:28:03,836 INFO exited: app (exit status 1; not expected)
2022-06-22 12:28:04,841 INFO spawned: 'app' with pid 47
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:28:05] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:28:05,741 INFO exited: app (exit status 1; not expected)
2022-06-22 12:28:07,746 INFO spawned: 'app' with pid 55
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:28:08] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:28:08,844 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:28:08,844 INFO exited: app (exit status 1; not expected)
2022-06-22 12:28:09,811 INFO spawned: 'app' with pid 63
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:28:10] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:28:10,869 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:28:10,869 INFO exited: app (exit status 1; not expected)
2022-06-22 12:28:11,872 INFO spawned: 'app' with pid 71
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:28:12] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:28:13,009 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:28:13,009 INFO exited: app (exit status 1; not expected)
2022-06-22 12:28:14,012 INFO spawned: 'app' with pid 79
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:28:14] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:28:15,091 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:28:15,091 INFO exited: app (exit status 1; not expected)
2022-06-22 12:28:16,093 INFO spawned: 'app' with pid 87
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:28:17] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:28:17,181 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:28:17,181 INFO exited: app (exit status 1; not expected)
2022-06-22 12:28:18,183 INFO spawned: 'app' with pid 95
2022-06-22 12:28:19,185 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:28:19] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:28:19,438 INFO exited: app (exit status 1; not expected)
2022-06-22 12:28:20,440 INFO spawned: 'app' with pid 103
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:28:21] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:28:21,550 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:28:21,551 INFO exited: app (exit status 1; not expected)
2022-06-22 12:28:22,552 INFO spawned: 'app' with pid 111
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:28:23] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:28:23,628 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:28:23,628 INFO exited: app (exit status 1; not expected)
2022-06-22 12:28:24,630 INFO spawned: 'app' with pid 119
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:28:25] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:28:25,740 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:28:25,740 INFO exited: app (exit status 1; not expected)
2022-06-22 12:28:26,743 INFO spawned: 'app' with pid 127
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:28:27] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:28:27,743 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:28:27,744 INFO exited: app (exit status 1; not expected)
2022-06-22 12:28:28,746 INFO spawned: 'app' with pid 135
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:28:29] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:28:29,737 INFO exited: app (exit status 1; not expected)
2022-06-22 12:28:30,739 INFO spawned: 'app' with pid 143
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:28:31] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:28:31,802 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:28:31,802 INFO exited: app (exit status 1; not expected)
2022-06-22 12:28:32,806 INFO spawned: 'app' with pid 151
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:28:33] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:28:33,696 INFO exited: app (exit status 1; not expected)
2022-06-22 12:28:34,700 INFO spawned: 'app' with pid 159
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:28:35] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:28:35,622 INFO exited: app (exit status 1; not expected)
2022-06-22 12:28:37,626 INFO spawned: 'app' with pid 167
2022-06-22 12:28:38,627 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:28:38] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:28:39,026 INFO exited: app (exit status 1; not expected)
2022-06-22 12:28:39,995 INFO spawned: 'app' with pid 175
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:28:40] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:28:41,143 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:28:41,143 INFO exited: app (exit status 1; not expected)
2022-06-22 12:28:42,145 INFO spawned: 'app' with pid 183
2022-06-22 12:28:43,148 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:28:43] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:28:43,419 INFO exited: app (exit status 1; not expected)
2022-06-22 12:28:44,422 INFO spawned: 'app' with pid 191
2022-06-22 12:28:45,425 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:28:45] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:28:45,677 INFO exited: app (exit status 1; not expected)
2022-06-22 12:28:46,679 INFO spawned: 'app' with pid 199
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:28:47] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:28:47,799 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 12:28:47,799 INFO exited: app (exit status 1; not expected)
2022-06-22 12:28:48,803 INFO spawned: 'app' with pid 207
2022-06-22 12:28:49,804 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:28:49] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:28:50,038 INFO exited: app (exit status 1; not expected)
2022-06-22 12:28:51,041 INFO spawned: 'app' with pid 215
2022-06-22 12:28:52,043 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:28:52] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:28:52,282 INFO exited: app (exit status 1; not expected)
2022-06-22 12:28:53,287 INFO spawned: 'app' with pid 223
2022-06-22 12:28:54,289 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 107, in register
    self.register_transition('await', Role.BOTH)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 22.06.22 12:28:54] [Level: fatal] source state aggregate_columns_to_drop not accessible for participants
2022-06-22 12:28:54,686 INFO exited: app (exit status 1; not expected)
2022-06-22 12:28:55,689 INFO spawned: 'app' with pid 231
