2022-06-21 12:31:54,421 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-06-21 12:31:54,423 INFO supervisord started with pid 8
2022-06-21 12:31:55,428 INFO spawned: 'nginx' with pid 11
2022-06-21 12:31:55,432 INFO spawned: 'app' with pid 12
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 13, in register
    self.register_transition('aggregate', Role.COORDINATOR)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 293, in register_transition
    self.log(f'target state {target} not found', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 21.06.22 12:31:55] [Level: fatal] target state aggregate not found
2022-06-21 12:31:55,854 INFO exited: app (exit status 1; not expected)
2022-06-21 12:31:56,857 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-21 12:31:56,860 INFO spawned: 'app' with pid 21
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 13, in register
    self.register_transition('aggregate', Role.COORDINATOR)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 293, in register_transition
    self.log(f'target state {target} not found', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 21.06.22 12:31:57] [Level: fatal] target state aggregate not found
2022-06-21 12:31:57,278 INFO exited: app (exit status 1; not expected)
2022-06-21 12:31:59,282 INFO spawned: 'app' with pid 26
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 13, in register
    self.register_transition('aggregate', Role.COORDINATOR)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 293, in register_transition
    self.log(f'target state {target} not found', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 21.06.22 12:31:59] [Level: fatal] target state aggregate not found
2022-06-21 12:31:59,719 INFO exited: app (exit status 1; not expected)
2022-06-21 12:32:02,726 INFO spawned: 'app' with pid 31
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 202, in register
    state.register()
  File "/app/states.py", line 13, in register
    self.register_transition('aggregate', Role.COORDINATOR)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 293, in register_transition
    self.log(f'target state {target} not found', level=LogLevel.FATAL)
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 21.06.22 12:32:03] [Level: fatal] target state aggregate not found
2022-06-21 12:32:03,291 INFO exited: app (exit status 1; not expected)
2022-06-21 12:32:04,293 INFO gave up: app entered FATAL state, too many start retries too quickly
